import os

def init():
    global isTrain, isModelChanged, model_file, dataset_folder, TrainedImages_folder_id, sample_folder_id, Model_folder_id, ALLOWED_IMAGE_EXTENSIONS, MAX_FILE_SIZE_MB, MAX_DISTANCE,LABEL_MAP
    model_file = "Server/EfficientNet"

    Model_folder_id = '1--KxQJhCkJ2kEBXW9u9uQt0QjoFh-mRl'

    ALLOWED_IMAGE_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}
    MAX_FILE_SIZE_MB = 50  # Set your maximum allowed file size in megabytes

    LABEL_OLD_MAP = {
      0: 'pink primrose',
      1: 'globe thistle',
      2: 'blanket flower',
      3: 'trumpet creeper',
      4: 'blackberry lily',
      5: 'snapdragon',
      6: "colt's foot",
      7: 'king protea',
      8: 'spear thistle',
      9: 'yellow iris',
      10: 'globe-flower',
      11: 'purple coneflower',
      12: 'peruvian lily',
      13: 'balloon flower',
      14: 'hard-leaved pocket orchid',
      15: 'giant white arum lily',
      16: 'fire lily',
      17: 'pincushion flower',
      18: 'fritillary',
      19: 'red ginger',
      20: 'grape hyacinth',
      21: 'corn poppy',
      22: 'prince of wales feathers',
      23: 'stemless gentian',
      24: 'artichoke',
      25: 'canterbury bells',
      26: 'sweet william',
      27: 'carnation',
      28: 'garden phlox',
      29: 'love in the mist',
      30: 'mexican aster',
      31: 'alpine sea holly',
      32: 'ruby-lipped cattleya',
      33: 'cape flower',
      34: 'great masterwort',
      35: 'siam tulip',
      36: 'sweet pea',
      37: 'lenten rose',
      38: 'barbeton daisy',
      39: 'daffodil',
      40: 'sword lily',
      41: 'poinsettia',
      42: 'bolero deep blue',
      43: 'wallflower',
      44: 'marigold',
      45: 'buttercup',
      46: 'oxeye daisy',
      47: 'english marigold',
      48: 'common dandelion',
      49: 'petunia',
      50: 'wild pansy',
      51: 'primula',
      52: 'sunflower',
      53: 'pelargonium',
      54: 'bishop of llandaff',
      55: 'gaura',
      56: 'geranium',
      57: 'orange dahlia',
      58: 'tiger lily',
      59: 'pink-yellow dahlia',
      60: 'cautleya spicata',
      61: 'japanese anemone',
      62: 'black-eyed susan',
      63: 'silverbush',
      64: 'californian poppy',
      65: 'osteospermum',
      66: 'spring crocus',
      67: 'bearded iris',
      68: 'windflower',
      69: 'moon orchid',
      70: 'tree poppy',
      71: 'gazania',
      72: 'azalea',
      73: 'water lily',
      74: 'rose',
      75: 'thorn apple',
      76: 'morning glory',
      77: 'passion flower',
      78: 'lotus lotus',
      79: 'toad lily',
      80: 'bird of paradise',
      81: 'anthurium',
      82: 'frangipani',
      83: 'clematis',
      84: 'hibiscus',
      85: 'columbine',
      86: 'desert-rose',
      87: 'tree mallow',
      88: 'magnolia',
      89: 'cyclamen',
      90: 'watercress',
      91: 'monkshood',
      92: 'canna lily',
      93: 'hippeastrum',
      94: 'bee balm',
      95: 'ball moss',
      96: 'foxglove',
      97: 'bougainvillea',
      98: 'camellia',
      99: 'mallow',
      100: 'mexican petunia',
      101: 'bromelia'
    }

    LABEL_MAP = {
        0: {'vietnamese_label': 'hoa anh thảo hồng', 'english_label': 'pink primrose'},
        1: {'vietnamese_label': 'hoa cúc thái', 'english_label': 'globe thistle'},
        2: {'vietnamese_label': 'hoa giấp tấm', 'english_label': 'blanket flower'},
        3: {'vietnamese_label': 'hoa bìm bìm', 'english_label': 'trumpet creeper'},
        4: {'vietnamese_label': 'hoa mắc cở', 'english_label': 'blackberry lily'},
        5: {'vietnamese_label': 'hoa lan ôn đới', 'english_label': 'snapdragon'},
        6: {'vietnamese_label': 'hoa bạch chỉ', 'english_label': "colt\'s foot"},
        7: {'vietnamese_label': 'hoa hồng vua', 'english_label': 'king protea'},
        8: {'vietnamese_label': 'hoa xương rồng', 'english_label': 'spear thistle'},
        9: {'vietnamese_label': 'hoa diên vỹ vàng', 'english_label': 'yellow iris'},
        10: {'vietnamese_label': 'hoa cúc đỏ', 'english_label':  'globe-flower'},
        11: {'vietnamese_label': 'hoa cúc tím', 'english_label':  'purple coneflower'},
        12: {'vietnamese_label': 'hoa lily peru', 'english_label':  'peruvian lily'},
        13: {'vietnamese_label': 'hoa bóng bụp', 'english_label':  'balloon flower'},
        14: {'vietnamese_label': 'hoa lan túi cài cứng', 'english_label':  'hard-leaved pocket orchid'},
        15: {'vietnamese_label': 'hoa cẩm tú cầu trắng khổng lồ', 'english_label':  'giant white arum lily'},
        16: {'vietnamese_label': 'hoa lily lửa', 'english_label':  'fire lily'},
        17: {'vietnamese_label': 'hoa cúc châm', 'english_label':  'pincushion flower'},
        18: {'vietnamese_label': 'hoa lily chết', 'english_label':  'fritillary'},
        19: {'vietnamese_label': 'gừng đỏ', 'english_label':  'red ginger'},
        20: {'vietnamese_label': 'hoa hyacinth nho', 'english_label':  'grape hyacinth'},
        21: {'vietnamese_label': 'hoa anh túc', 'english_label':  'corn poppy'},
        22: {'vietnamese_label': 'hoa hoàng anh', 'english_label':  'prince of wales feathers'},
        23: {'vietnamese_label': 'hoa long não không thân', 'english_label':  'stemless gentian'},
        24: {'vietnamese_label': 'hoa atisô', 'english_label':  'artichoke'},
        25: {'vietnamese_label': 'hoa chuông canterbury', 'english_label':  'canterbury bells'},
        26: {'vietnamese_label': 'hoa william ngọt', 'english_label':  'sweet william'},
        27: {'vietnamese_label': 'hoa cẩm chướng', 'english_label':  'carnation'},
        28: {'vietnamese_label': 'hoa thảo vườn', 'english_label':  'garden phlox'},
        29: {'vietnamese_label': 'hoa yêu trong sương mù', 'english_label':  'love in the mist'},
        30: {'vietnamese_label': 'hoa tần bì mexico', 'english_label':  'mexican aster'},
        31: {'vietnamese_label': 'hoa bách xù alpine', 'english_label':  'alpine sea holly'},
        32: {'vietnamese_label': 'hoa cát tường môi đỏ', 'english_label':  'ruby-lipped cattleya'},
        33: {'vietnamese_label': 'hoa hoa mũi tên', 'english_label':  'cape flower'},
        34: {'vietnamese_label': 'hoa masterwort vĩ đại', 'english_label':  'great masterwort'},
        35: {'vietnamese_label': 'hoa tulip siam', 'english_label':  'siam tulip'},
        36: {'vietnamese_label': 'hoa đậu nành', 'english_label':  'sweet pea'},
        37: {'vietnamese_label': 'hoa giáng sinh', 'english_label':  'lenten rose'},
        38: {'vietnamese_label': 'hoa cúc barbeton', 'english_label':  'barbeton daisy'},
        39: {'vietnamese_label': 'hoa thủy tiên', 'english_label':  'daffodil'},
        40: {'vietnamese_label': 'hoa đại đao', 'english_label':  'sword lily'},
        41: {'vietnamese_label': 'hoa đại lễ', 'english_label':  'poinsettia'},
        42: {'vietnamese_label': 'hoa bolero màu xanh sâu', 'english_label':  'bolero deep blue'},
        43: {'vietnamese_label': 'hoa tường vy', 'english_label':  'wallflower'},
        44: {'vietnamese_label': 'hoa vạn thọ', 'english_label':  'marigold'},
        45: {'vietnamese_label': 'hoa bất tử', 'english_label':  'buttercup'},
        46: {'vietnamese_label': 'hoa dã quỳ', 'english_label':  'oxeye daisy'},
        47: {'vietnamese_label': 'hoa vạn thọ anh', 'english_label':  'english marigold'},
        48: {'vietnamese_label': 'bồ công anh thường gặp', 'english_label':  'common dandelion'},
        49: {'vietnamese_label': 'hoa petunia', 'english_label':  'petunia'},
        50: {'vietnamese_label': 'hoa hoa giấy hoang dã', 'english_label':  'wild pansy'},
        51: {'vietnamese_label': 'hoa hoàng liên', 'english_label':  'primula'},
        52: {'vietnamese_label': 'hoa hướng dương', 'english_label':  'sunflower'},
        53: {'vietnamese_label': 'hoa phong lữ', 'english_label':  'pelargonium'},
        54: {'vietnamese_label': 'giáo sư llandaff', 'english_label':  'bishop of llandaff'},
        55: {'vietnamese_label': 'hoa gaura', 'english_label':  'gaura'},
        56: {'vietnamese_label': 'hoa dạ lan', 'english_label':  'geranium'},
        57: {'vietnamese_label': 'hoa dahlia cam', 'english_label':  'orange dahlia'},
        58: {'vietnamese_label': 'hoa hoa hổ', 'english_label':  'tiger lily'},
        59: {'vietnamese_label': 'hoa dahlia hồng vàng', 'english_label':  'pink-yellow dahlia'},
        60: {'vietnamese_label': 'hoa cautleya spicata', 'english_label':  'cautleya spicata'},
        61: {'vietnamese_label': 'hoa cánh cụt nhật bản', 'english_label':  'japanese anemone'},
        62: {'vietnamese_label': 'hoa đen mắt susan', 'english_label':  'black-eyed susan'},
        63: {'vietnamese_label': 'bụi bạc', 'english_label':  'silverbush'},
        64: {'vietnamese_label': 'hoa anh túc californian', 'english_label':  'californian poppy'},
        65: {'vietnamese_label': 'hoa bưởi', 'english_label':  'osteospermum'},
        66: {'vietnamese_label': 'hoa anh thảo mùa xuân', 'english_label':  'spring crocus'},
        67: {'vietnamese_label': 'hoa diên vỹ có râu', 'english_label':  'bearded iris'},
        68: {'vietnamese_label': 'hoa hoa gió', 'english_label':  'windflower'},
        69: {'vietnamese_label': 'hoa moon orchid', 'english_label':  'moon orchid'},
        70: {'vietnamese_label': 'hoa hoa dã quỳ', 'english_label':  'tree poppy'},
        71: {'vietnamese_label': 'hoa gazania', 'english_label':  'gazania'},
        72: {'vietnamese_label': 'hoa azalea', 'english_label':  'azalea'},
        73: {'vietnamese_label': 'hoa súng nước', 'english_label':  'water lily'},
        74: {'vietnamese_label': 'hoa hồng', 'english_label':  'rose'},
        75: {'vietnamese_label': 'hoa dây gai', 'english_label':  'thorn apple'},
        76: {'vietnamese_label': 'hoa buổi sáng', 'english_label':  'morning glory'},
        77: {'vietnamese_label': 'hoa đam bầu', 'english_label':  'passion flower'},
        78: {'vietnamese_label': 'hoa sen', 'english_label':  'lotus lotus'},
        79: {'vietnamese_label': 'hoa lạc đà', 'english_label':  'toad lily'},
        80: {'vietnamese_label': 'hoa chim cánh cụt', 'english_label':  'bird of paradise'},
        81: {'vietnamese_label': 'hoa hoa sói', 'english_label':  'anthurium'},
        82: {'vietnamese_label': 'hoa cây đại', 'english_label':  'frangipani'},
        83: {'vietnamese_label': 'hoa bách tán', 'english_label':  'clematis'},
        84: {'vietnamese_label': 'hoa dâm bụt', 'english_label':  'hibiscus'},
        85: {'vietnamese_label': 'hoa bách quả', 'english_label':  'columbine'},
        86: {'vietnamese_label': 'hoa hồng sa mạc', 'english_label':  'desert-rose'},
        87: {'vietnamese_label': 'hoa cây nha đam', 'english_label':  'tree mallow'},
        88: {'vietnamese_label': 'hoa mộc lan', 'english_label':  'magnolia'},
        89: {'vietnamese_label': 'hoa cyclamen', 'english_label':  'cyclamen'},
        90: {'vietnamese_label': 'cải xoong', 'english_label':  'watercress'},
        91: {'vietnamese_label': 'hoa độc đầu', 'english_label':  'monkshood'},
        92: {'vietnamese_label': 'hoa cát tường canna', 'english_label':  'canna lily'},
        93: {'vietnamese_label': 'hoa amaryllis', 'english_label':  'hippeastrum'},
        94: {'vietnamese_label': 'hoa thơm', 'english_label':  'bee balm'},
        95: {'vietnamese_label': 'bóng cỏ', 'english_label':  'ball moss'},
        96: {'vietnamese_label': 'hoa thạch thảo', 'english_label':  'foxglove'},
        97: {'vietnamese_label': 'hoa giấy vạn lý trường thành', 'english_label':  'bougainvillea'},
        98: {'vietnamese_label': 'hoa trà', 'english_label':  'camellia'},
        99: {'vietnamese_label': 'hoa cẩm tú cầu', 'english_label':  'mallow'},
        100: {'vietnamese_label': 'hoa petunia mexico', 'english_label': 'mexican petunia'},
        101: {'vietnamese_label': 'bromeli', 'english_label': 'bromelia'}
    }




    if os.path.exists(model_file):
        isTrain = True
    else:
        isTrain = False

    isModelChanged = True